include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    # Exclude generated files from analysis
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbserver.dart"
    - "**/*.pbjson.dart"

linter:
  rules:
    public_member_api_docs: true
